version: '3'
services:
    ministub:
        container_name: ministub
        build:
            context: .
            dockerfile: Dockerfile
        image: ministub:0.0.1
        command: "/code/ministub /schemas/testapi.yml"
        volumes:
            - ./examples:/schemas
        ports:
            - 6006:8080