version: '3'
networks:
    app-net:
        internal: false
services:
    ministub:
        container_name: ministub
        build:
            context: .
            dockerfile: Dockerfile
        image: mw/ministub:0.0.1
        networks:
            - app-net
        ports:
            - 6006:80